### ISSUE TITLE
Using X-Forwarded-For and bad formatted icon

### ISSUE THREAD

**Issue by sirovermark** [TimoKunze/files_trackdownloads#18]
Hi guys!

First of all, thanks for your app!

I have Nextcloud 20 behind a HAProxy with the X-Fordered-For tag turned on. I've been looking for this error for a while but haven't seen any related.

When I check the activity app I can only see the internal IP and not the public one because I guess it doesn't check if the X-Forwared-For field exists. I have Geoblocker and other applications activated and of course they can handle it correctly. I have checked the NGINX logs, just in case, and the public IP is there.

I was wondering if something can be done to check **if X-Forwared-For is there and use it**.

There is something else, but this one is pretty simple, it doesn't bother at all but it's weird. User icon is badly formatted and there is a parentheses right after the letter
![image](https://user-images.githubusercontent.com/30412009/103075898-d4c11280-45cc-11eb-89b3-fdd7b466057f.png)

Cheers!

**Comment by TimoKunze** [comment]
Hi, to be honest I'm not using this plugin myself anymore because in my company we don't have this requirement anymore.

I had a look into the code and I can see where the malformed icon comes from. Last year somebody asked to also log the IP (see #10). I decided to append the IP to the user name. Nextcloud generates those avatars from the usernames, taking the first character of the user's first name and last name. If your username consists of only one word (ilo), the paranthesis from the IP is interpreted as the first character of the user's last name.

I'm trying to implement IP logging in a different way, but could not yet make it work.

Once this issue is solved, I'll have a look at X-Forwared-For.

**Comment by sirovermark** [comment]
Thanks @TimoKunze!

**Comment by TimoKunze** [comment]
Version 1.10.0 supports X-Forwarded-For. However, I cannot test it myself.

**Comment by sirovermark** [comment]
Thank you @TimoKunze! No worries! Let me try and I'll give you feedback.

**Comment by sirovermark** [comment]
So far so good @TimoKunze! Now I can see the public IP and not the masked one. Great job! Thank you! :)
